admin_makerconfig_index:
  path: /bundle
  controller: 'MartenaSoft\Maker\Controller\CreateBundleController::index'

admin_makerconfig_edit:
  path: /bundle/edit/{slug}
  controller: 'MartenaSoft\Maker\Controller\CreateBundleController::save'

admin_makerconfig_create:
  path: /bundle/create
  controller: 'MartenaSoft\Maker\Controller\CreateBundleController::create'


admin_makermodule_index:
  path: /module
  controller: 'MartenaSoft\Maker\Controller\ModuleController::index'


admin_maker_entity_index:
  path: /entity
  controller: 'MartenaSoft\Maker\Controller\EntityController::index'

admin_maker_entity_create:
  path: /entity/create
  controller: 'MartenaSoft\Maker\Controller\EntityController::create'
